### ISSUE TITLE
Some problems starting a session with the power supply

### ISSUE THREAD

**Issue by rolandvs** [kudl4t4/RIGOL-DP832-GUI#1]
Beautiful piece of software. Installed on OSX and run into some problems. I did manage to get it working (so now I can check on why it isn't working out of the box):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyvisa/highlevel.py", line 159, in get_last_status_in_session
    return self._last_status_in_session[session]
KeyError: 9673708

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RIGOL_DP832_GUI.py", line 848, in <lambda>
    self.main_btn_connect.clicked.connect(lambda:self.main_connect())
  File "RIGOL_DP832_GUI.py", line 1778, in main_connect
    if self.main_rigol_rm.last_status == 0:
  File "/usr/local/lib/python3.7/site-packages/pyvisa/highlevel.py", line 1579, in last_status
    return self.visalib.get_last_status_in_session(self.session)
  File "/usr/local/lib/python3.7/site-packages/pyvisa/highlevel.py", line 161, in get_last_status_in_session
    raise errors.Error('The session %r does not seem to be valid as it does not have any last status' % session)
pyvisa.errors.Error: The session 9673708 does not seem to be valid as it does not have any last status
Abort trap: 6
```

So I just replaced ```if self.main_rigol_rm.last_status == 0:``` for ```if True:``` and got it to work...

**Comment by ringo458** [comment]
I had the exact same problem in centos7. I did something similar. I also got a warning like ovp used before set. I have python 3.63

**Comment by ringo458** [comment]
also centos doesn't have ni-visa as a backend and you have to use pyvisa-py which requires that the resourcemanager call be made with the argument '@py'
Since the other interaction with resourcemanager is not used I guess I wonder if the call is even necessary but I am only using this to get an elucidation of commands that work using visa debug so I may not find out
